// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRt0YvrfdBffRVCXE8Od3ftzzertIeYP0',
    appId: '1:1084017196899:web:ca5da93f158741aa7c1d56',
    messagingSenderId: '1084017196899',
    projectId: 'ynagella-cmsc5303-flutterdev',
    authDomain: 'ynagella-cmsc5303-flutterdev.firebaseapp.com',
    storageBucket: 'ynagella-cmsc5303-flutterdev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2UroHYx0aJi4thMumpgQ3P2O1Akh9hFI',
    appId: '1:1084017196899:android:b0b5a9e94261424b7c1d56',
    messagingSenderId: '1084017196899',
    projectId: 'ynagella-cmsc5303-flutterdev',
    storageBucket: 'ynagella-cmsc5303-flutterdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR8_ke5hb5q50ByZNK_9x-ebjXJM4ViiM',
    appId: '1:1084017196899:ios:69bd7490f44668dc7c1d56',
    messagingSenderId: '1084017196899',
    projectId: 'ynagella-cmsc5303-flutterdev',
    storageBucket: 'ynagella-cmsc5303-flutterdev.appspot.com',
    iosBundleId: 'edu.uco.ynagella.cmsc5303.lesson6',
  );

}