// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Needs to be replaced with actual values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API-KEY',
    appId: 'Replace-app-ID',
    messagingSenderId: 'Replace-messaging-sender-ID',
    projectId: 'Replace-project-ID',
    authDomain: 'Replace-auth-domain',
    storageBucket: 'Replace-storage-bucket',
    measurementId: 'Replace-measurement-ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API-KEY',
    appId: 'Replace-app-ID',
    messagingSenderId: 'Replace-messaging-sender-ID',
    projectId: 'Replace-project-ID',
    storageBucket: 'Replace-storage-bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API-KEY',
    appId: 'Replace-app-ID',
    messagingSenderId: 'Replace-messaging-sender-ID',
    projectId: 'Replace-project-ID',
    storageBucket: 'Replace-storage-bucket',
    iosBundleId: 'Replace-ios-bundle-ID',
  );

}